singleServerConfig:
    address: redis://127.0.0.1:6379
    clientName: ''
    connectTimeout: 10000
    connectionMinimumIdleSize: 10
    connectionPoolSize: 64
    database: 0
    dnsMonitoringInterval: 5000
    idleConnectionTimeout: 10000
    password: null
    retryAttempts: 3
    retryInterval: 1500
    subscriptionConnectionMinimumIdleSize: 1
    subscriptionConnectionPoolSize: 50
    subscriptionsPerConnection: 5
    timeout: 3000
