apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-app-internal-ingress
  namespace: sample-app
  annotations:
    kubernetes.io/ingress.class: "gce-internal"
spec:
  defaultBackend:
    service:
      name: hello-app-internal
      port:
        number: 8080
