apiVersion: v1
kind: Service
metadata:
  name: hello-app-internal-app
  labels:
    run: hello-app-internal-app
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-app
